const dummyData = {
   workspaces: ["INBOX", "HOMEWORK", "PROJECTS"],
   view: "INBOX",
   bookmarks: [
      {
         name: "React",
         user: "facebook",
         repo: "react",
         stars: 186000,
         forks: 38300,
         issues: {
            open: 672,
            closed: 10657,
         },
         created: "2013-02-07",
         updated: "2022-29-03",
         url: "https://github.com/facebook/react",
         workspace: "INBOX",
      },
      {
         name: "Zustand",
         user: "pmndrs",
         repo: "zustand",
         stars: 16000,
         forks: 458,
         issues: {
            open: 22,
            closed: 369,
         },
         created: "2019-11-10",
         updated: "2022-07-04",
         url: "https://github.com/pmndrs/zustand",
         workspace: "HOMEWORK"
      },
      {
         name: "NextJS",
         user: "vercel",
         repo: "next.js",
         stars: 85300,
         forks: 17900,
         issues: {
            open: 949,
            closed: 11475,
         },
         created: "2016-25-10",
         updated: "2022-12-04",
         url: "https://github.com/vercel/next.js",
         workspace: "PROJECTS",
      },
      {
         name: "docker",
         user: "jenkinsci",
         repo: "docker",
         stars: 5100,
         forks: 3700,
         issues: {
            open: 36,
            closed: 585,
         },
         created: "2020-18-06",
         updated: "2019-13-03",
         url: "https://github.com/jenkinsci/docker",
         workspace: "PROJECTS"
      },
      {
         name: "TypeScript",
         user: "microsoft",
         repo: "typescript",
         stars: 79700,
         forks: 10500,
         issues: {
            open: 5000,
            closed: 28098,
         },
         created: "2022-13-04",
         updated: "2014-07-10",
         url: "https://github.com/microsoft/TypeScript",
         workspace: "INBOX"
      },
      {
         name: "motion",
         user: "framer",
         repo: "motion",
         stars: 14300,
         forks: 425,
         issues: {
            open: 180,
            closed: 761,
         },
         created: "2022-13-04",
         updated: "2019-09-11",
         url: "https://github.com/framer/motion",
         workspace: "PROJECTS",
      },
      {
         name: "motion",
         user: "framer",
         repo: "motion",
         stars: 14300,
         forks: 425,
         issues: {
            open: 180,
            closed: 761,
         },
         created: "2022-13-04",
         updated: "2019-09-11",
         url: "https://github.com/framer/motion",
         workspace: "PROJECTS",
      },
      {
         name: "motion",
         user: "framer",
         repo: "motion",
         stars: 14300,
         forks: 425,
         issues: {
            open: 180,
            closed: 761,
         },
         created: "2022-13-04",
         updated: "2019-09-11",
         url: "https://github.com/framer/motion",
         workspace: "PROJECTS",
      },
      {
         name: "motion",
         user: "framer",
         repo: "motion",
         stars: 14300,
         forks: 425,
         issues: {
            open: 180,
            closed: 761,
         },
         created: "2022-13-04",
         updated: "2019-09-11",
         url: "https://github.com/framer/motion",
         workspace: "PROJECTS",
      },
      {
         name: "motion",
         user: "framer",
         repo: "motion",
         stars: 14300,
         forks: 425,
         issues: {
            open: 180,
            closed: 761,
         },
         created: "2022-13-04",
         updated: "2019-09-11",
         url: "https://github.com/framer/motion",
         workspace: "PROJECTS",
      },
      {
         name: "motion",
         user: "framer",
         repo: "motion",
         stars: 14300,
         forks: 425,
         issues: {
            open: 180,
            closed: 761,
         },
         created: "2022-13-04",
         updated: "2019-09-11",
         url: "https://github.com/framer/motion",
         workspace: "PROJECTS",
      },
      {
         name: "motion",
         user: "framer",
         repo: "motion",
         stars: 14300,
         forks: 425,
         issues: {
            open: 180,
            closed: 761,
         },
         created: "2022-13-04",
         updated: "2019-09-11",
         url: "https://github.com/framer/motion",
         workspace: "PROJECTS",
      },
      {
         name: "motion",
         user: "framer",
         repo: "motion",
         stars: 14300,
         forks: 425,
         issues: {
            open: 180,
            closed: 761,
         },
         created: "2022-13-04",
         updated: "2019-09-11",
         url: "https://github.com/framer/motion",
         workspace: "PROJECTS",
      },
      {
         name: "motion",
         user: "framer",
         repo: "motion",
         stars: 14300,
         forks: 425,
         issues: {
            open: 180,
            closed: 761,
         },
         created: "2022-13-04",
         updated: "2019-09-11",
         url: "https://github.com/framer/motion",
         workspace: "PROJECTS",
      },
      {
         name: "motion",
         user: "framer",
         repo: "motion",
         stars: 14300,
         forks: 425,
         issues: {
            open: 180,
            closed: 761,
         },
         created: "2022-13-04",
         updated: "2019-09-11",
         url: "https://github.com/framer/motion",
         workspace: "PROJECTS",
      },
      {
         name: "motion",
         user: "framer",
         repo: "motion",
         stars: 14300,
         forks: 425,
         issues: {
            open: 180,
            closed: 761,
         },
         created: "2022-13-04",
         updated: "2019-09-11",
         url: "https://github.com/framer/motion",
         workspace: "PROJECTS",
      }
   ],
}

export default dummyData;